apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  # all argo apps need to be in same namespace as argocd pods
  namespace: argocd
spec:
  # projects used to scope permissions to repos and/or clusters 
  project: default
  source:
    repoURL: https://github.com/chestercodes/argocd-demo.git
    # can be any git ref
    targetRevision: HEAD
    path: charts/argo-cd
    helm:
      valueFiles:
      # file relative to path dir
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    # destination namespace
    namespace: argocd
