apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dotnet-sample-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`dotnet-sample-127-0-0-1.nip.io`)
      priority: 10
      services:
        - name: dotnet-sample
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-sample
spec:
  ports:
    - port: 8080
  selector:
    app: dotnet-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-sample
  template:
    metadata:
      labels:
        app: dotnet-sample
    spec:
      containers:
        - name: app
          image: mcr.microsoft.com/dotnet/samples:aspnetapp
          ports:
            - containerPort: 8080