apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: argocd-demo
servers: 1
agents: 1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
