argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
  configs:
    cm:
      create: true
    params:
      create: true
      server.insecure: true
    secret:
      # hiargo
      argocdServerAdminPassword: "$2a$10$c3gqRsiIe9tzcTfBWkJ6t.Trv6iUsZnZhTohh1FtNNgxY4DZ.FqiC"
      argocdServerAdminPasswordMtime: ""
